Update dependencies to fix compile error
Without this version bump the following error happens at compile time:

```
Compiling tests-output/clojure/string.cljs to tests-output/clojure/string.js
 :cause 'com.cognitect.transit.Writer com.cognitect.transit.TransitFactory.writer(com.cognitect.transit.TransitFactory$Format, java.io.OutputStream, java.util.Map, com.cognitect.transit.WriteHandler, java.util.function.Function)'
 :via
 [{:type java.lang.NoSuchMethodError
   :message 'com.cognitect.transit.Writer com.cognitect.transit.TransitFactory.writer(com.cognitect.transit.TransitFactory$Format, java.io.OutputStream, java.util.Map, com.cognitect.transit.WriteHandler, java.util.function.Function)'
   :at [cognitect.transit$writer invokeStatic transit.clj 157]}]
 :trace
 [[cognitect.transit$writer invokeStatic transit.clj 157]
  [cognitect.transit$writer invoke transit.clj 139]
  [cljs.analyzer$write_analysis_cache$fn__2982 invoke analyzer.cljc 4659]
  [cljs.analyzer$write_analysis_cache invokeStatic analyzer.cljc 4658]
  [cljs.analyzer$write_analysis_cache invoke analyzer.cljc 4645]
  <... rest of the output removed ...>
```